services:
  - type: web
    name: coldmail-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: IS_DEVELOPMENT
        value: false